"""Differentiable process-simulation layer for Fugacio (depends on ``fugacio.thermo``).

The layer provides:

* `Stream`: the differentiable material stream passed between units;
* a stream property bridge (`enthalpy_flow`, `entropy_flow`,
  `molar_enthalpy`, `molar_entropy`, `mass_flow`) that gives any
  stream a two-phase-aware enthalpy/entropy via `fugacio.thermo`;
* unit operations with rigorous material *and* energy balances
  (`flash_drum`, `heater`, `valve`, `pump`,
  `compressor`, `turbine`, `mix`, `splitter`,
  `component_separator`);
* a thermodynamic-model bridge (`eos_model_for`, `nrtl_model_for`,
  `uniquac_model_for`, `unifac_model_for`, `saft_model_for`) that turns
  component names into a ready EOS, gamma-phi, or PC-SAFT `EquilibriumModel`;
* non-ideal separation units (`flash_vle`, `decanter`,
  `three_phase_flash`) and binary diagram / azeotrope / residue-curve helpers
  (`pxy_diagram`, `txy_diagram`, `azeotrope_pressure`,
  `azeotrope_temperature`, `residue_curve`, `residue_curve_map`);
* reactor unit operations (`equilibrium_reactor`,
  `stoichiometric_reactor`, `cstr`, `pfr`,
  `batch_reactor`) and reactive separations (`reactive_flash`,
  `reactive_distillation`);
* a differentiable optimization toolkit (`minimize`, `argmin`,
  `least_squares`) that differentiates *through the optimum* by the
  implicit function theorem;
* design specifications and set-point controllers (`meet_spec`,
  `solve_design`, `controller`) that adjust a degree of freedom to
  hit a target, plus end-to-end flowsheet optimization (`optimize_flowsheet`);
* equipment sizing, Turton bare-module costing, utility pricing, and financial
  metrics (`heat_exchanger_area`, `bare_module_cost`,
  `utility_cost`, `total_annual_cost`, `npv`) for money-valued
  design objectives;
* differentiable heat integration / pinch analysis (`pinch_analysis`,
  `composite_curves`, `grand_composite_curve`, `area_target`,
  `optimal_dt_min`, `synthesize_network`) for minimum-utility targets
  and heat-exchanger-network synthesis (see `fugacio.sim.integration`);
* advanced process control: model predictive control and state estimation
  (`linear_mpc`, `nonlinear_mpc`, `solve_qp`, `dare`,
  `lqr`, `kalman_gain`, `KalmanFilter`,
  `ExtendedKalmanFilter`, `UnscentedKalmanFilter`,
  `moving_horizon_estimate`, `simulate_closed_loop`,
  `tune_mpc`), differentiable end to end, so the controller weights are
  tunable by gradient descent (see `fugacio.sim.mpc`);
* physical steam/cooling-water utilities on IAPWS-95 steam tables
  (`steam_heating`, `cooling_water`, `steam_turbine`,
  `condensate_flash_fraction`) for utility balances with real latent
  heats, differentiable end to end;
* the original lightweight modified-Raoult helpers (`bubble_pressure`,
  `antoine_psat`).
"""

from fugacio.sim.column import (
    ColumnResult,
    ShortcutResult,
    fenske_min_stages,
    gilliland_stages,
    kirkbride_feed_stage,
    relative_volatility,
    shortcut_column,
    solve_column,
    underwood_min_reflux,
)

# Dynamic simulation & control (time-domain). Imported last; these layers build on
# the steady-state engine above (control depends on the optimizers, the dynamic
# units on the thermodynamic property bridge).
from fugacio.sim.control import (
    PID,
    FOPDTModel,
    PIDState,
    StateSpace,
    StepInfo,
    amigo,
    bode,
    cohen_coon,
    dc_gain,
    first_order_step,
    fit_fopdt,
    fopdt_step,
    frequency_response,
    iae,
    imc_tuning,
    is_stable,
    ise,
    itae,
    linearize,
    overshoot,
    p_only,
    pi,
    poles,
    rise_time,
    second_order_step,
    settling_time,
    step_info,
    ziegler_nichols,
)
from fugacio.sim.design import (
    DesignSpec,
    FlowsheetOptResult,
    SpecResult,
    controller,
    meet_spec,
    optimize_flowsheet,
    solve_design,
)
from fugacio.sim.diagrams import (
    AzeotropeResult,
    PxyDiagram,
    ResidueCurve,
    TxyDiagram,
    azeotrope_pressure,
    azeotrope_temperature,
    pxy_diagram,
    residue_curve,
    residue_curve_map,
    txy_diagram,
)
from fugacio.sim.dynamics import (
    DynamicCSTR,
    DynamicEstimateResult,
    DynamicFlash,
    DynamicFlowsheet,
    DynamicResult,
    DynamicUnit,
    GasReceiver,
    LevelTank,
    MixingTank,
    ODEResult,
    OptimalControlResult,
    ThermalMass,
    estimate_dynamics,
    integrate,
    odeint,
    odeint_final,
    optimal_control,
    simulate,
    tune_pid,
)
from fugacio.sim.economics import (
    CEPCI_DEFAULT,
    CEPCI_REF,
    EquipmentCost,
    Utility,
    annualized_capital,
    bare_module_cost,
    capital_recovery_factor,
    column_diameter,
    column_height,
    cylinder_volume,
    discounted_payback,
    heat_exchanger_area,
    installed_capital,
    lmtd,
    npv,
    pressure_factor,
    purchased_cost,
    total_annual_cost,
    utility_cost,
    vapor_molar_volume_ideal,
    vessel_volume,
)

# Equation-oriented flowsheeting (simultaneous solve). Imported last; it builds on
# the streams, units (for forward initialisation), the property bridge, and the
# differentiable Newton solver, and is an alternative to the sequential-modular
# engine above.
from fugacio.sim.eo import (
    Block,
    ComponentSeparator,
    Compressor,
    Context,
    DOFReport,
    EOFlowsheet,
    EOOptResult,
    EOSolution,
    Flash,
    Heater,
    Mixer,
    Pump,
    Scales,
    Splitter,
    Turbine,
    Valve,
    optimize_flowsheet_eo,
)
from fugacio.sim.flowsheet import Flowsheet, tear_solve
from fugacio.sim.integration import (
    CompositeCurves,
    Exchanger,
    GrandComposite,
    HeatCascade,
    HeatExchangerNetwork,
    HeatStream,
    OptimalDtMin,
    PinchResult,
    SuperTargetResult,
    UnitsTarget,
    area_target,
    capital_cost_target,
    composite_curves,
    grand_composite_curve,
    heat_cascade,
    heat_stream,
    make_stream,
    minimum_utilities,
    optimal_dt_min,
    pinch_analysis,
    supertarget,
    synthesize_network,
    total_annual_cost_target,
    units_target,
    verify_network,
)
from fugacio.sim.models import (
    UnifacModel,
    eos_model_for,
    nrtl_model_for,
    saft_model_for,
    unifac_model_for,
    uniquac_model_for,
)

# Advanced process control (model predictive control + state estimation). Builds on
# the optimizers, the state-space linearization in ``control`` and the differentiable
# integrator in ``dynamics``.
from fugacio.sim.mpc import (
    ClosedLoop,
    ExtendedKalmanFilter,
    GaussianState,
    KalmanFilter,
    LinearMPC,
    MHEResult,
    MPCResult,
    MPCState,
    NMPCResult,
    NonlinearMPC,
    QPSettings,
    QPSolution,
    UnscentedKalmanFilter,
    c2d,
    care,
    closed_loop_cost,
    constant_setpoint,
    dare,
    discretize,
    dlqr,
    kalman_gain,
    linear_feedback,
    linear_mpc,
    lqr,
    moving_horizon_estimate,
    nonlinear_feedback,
    nonlinear_mpc,
    quadratic_tracking,
    simulate_closed_loop,
    solve_qp,
    solve_qp_canonical,
    tune_mpc,
)
from fugacio.sim.optimize import (
    OptimizeResult,
    argmin,
    least_squares,
    minimize,
)
from fugacio.sim.properties import (
    column_diameter_for,
    enthalpy_flow,
    entropy_flow,
    liquid_density,
    liquid_thermal_conductivity,
    liquid_viscosity,
    liquid_volumetric_flow,
    mass_flow,
    molar_enthalpy,
    molar_entropy,
    molar_mass,
    surface_tension,
    vapor_density,
    vapor_thermal_conductivity,
    vapor_viscosity,
    vapor_volumetric_flow,
)
from fugacio.sim.reactive import (
    ReactiveColumnResult,
    ReactiveFlashResult,
    reactive_distillation,
    reactive_flash,
)
from fugacio.sim.reactors import (
    ReactorResult,
    batch_reactor,
    conversion,
    cstr,
    equilibrium_reactor,
    pfr,
    stoichiometric_reactor,
)
from fugacio.sim.separations import decanter, flash_vle, three_phase_flash
from fugacio.sim.stream import Stream
from fugacio.sim.units import (
    HeaterResult,
    PumpResult,
    WorkResult,
    component_separator,
    compressor,
    flash_drum,
    heater,
    mix,
    pump,
    splitter,
    turbine,
    valve,
)
from fugacio.sim.utilities import (
    STEAM_LEVELS,
    CoolingWaterResult,
    SteamHeatingResult,
    SteamTurbineResult,
    condensate_flash_fraction,
    cooling_water,
    saturated_steam_temperature,
    steam_enthalpy,
    steam_heating,
    steam_quality_after_letdown,
    steam_turbine,
)
from fugacio.sim.vle import antoine_psat, bubble_pressure

__all__ = [
    "CEPCI_DEFAULT",
    "CEPCI_REF",
    "PID",
    "STEAM_LEVELS",
    "AzeotropeResult",
    "Block",
    "ClosedLoop",
    "ColumnResult",
    "ComponentSeparator",
    "CompositeCurves",
    "Compressor",
    "Context",
    "CoolingWaterResult",
    "DOFReport",
    "DesignSpec",
    "DynamicCSTR",
    "DynamicEstimateResult",
    "DynamicFlash",
    "DynamicFlowsheet",
    "DynamicResult",
    "DynamicUnit",
    "EOFlowsheet",
    "EOOptResult",
    "EOSolution",
    "EquipmentCost",
    "Exchanger",
    "ExtendedKalmanFilter",
    "FOPDTModel",
    "Flash",
    "Flowsheet",
    "FlowsheetOptResult",
    "GasReceiver",
    "GaussianState",
    "GrandComposite",
    "HeatCascade",
    "HeatExchangerNetwork",
    "HeatStream",
    "Heater",
    "HeaterResult",
    "KalmanFilter",
    "LevelTank",
    "LinearMPC",
    "MHEResult",
    "MPCResult",
    "MPCState",
    "Mixer",
    "MixingTank",
    "NMPCResult",
    "NonlinearMPC",
    "ODEResult",
    "OptimalControlResult",
    "OptimalDtMin",
    "OptimizeResult",
    "PIDState",
    "PinchResult",
    "Pump",
    "PumpResult",
    "PxyDiagram",
    "QPSettings",
    "QPSolution",
    "ReactiveColumnResult",
    "ReactiveFlashResult",
    "ReactorResult",
    "ResidueCurve",
    "Scales",
    "ShortcutResult",
    "SpecResult",
    "Splitter",
    "StateSpace",
    "SteamHeatingResult",
    "SteamTurbineResult",
    "StepInfo",
    "Stream",
    "SuperTargetResult",
    "ThermalMass",
    "Turbine",
    "TxyDiagram",
    "UnifacModel",
    "UnitsTarget",
    "UnscentedKalmanFilter",
    "Utility",
    "Valve",
    "WorkResult",
    "amigo",
    "annualized_capital",
    "antoine_psat",
    "area_target",
    "argmin",
    "azeotrope_pressure",
    "azeotrope_temperature",
    "bare_module_cost",
    "batch_reactor",
    "bode",
    "bubble_pressure",
    "c2d",
    "capital_cost_target",
    "capital_recovery_factor",
    "care",
    "closed_loop_cost",
    "cohen_coon",
    "column_diameter",
    "column_diameter_for",
    "column_height",
    "component_separator",
    "composite_curves",
    "compressor",
    "condensate_flash_fraction",
    "constant_setpoint",
    "controller",
    "conversion",
    "cooling_water",
    "cstr",
    "cylinder_volume",
    "dare",
    "dc_gain",
    "decanter",
    "discounted_payback",
    "discretize",
    "dlqr",
    "enthalpy_flow",
    "entropy_flow",
    "eos_model_for",
    "equilibrium_reactor",
    "estimate_dynamics",
    "fenske_min_stages",
    "first_order_step",
    "fit_fopdt",
    "flash_drum",
    "flash_vle",
    "fopdt_step",
    "frequency_response",
    "gilliland_stages",
    "grand_composite_curve",
    "heat_cascade",
    "heat_exchanger_area",
    "heat_stream",
    "heater",
    "iae",
    "imc_tuning",
    "installed_capital",
    "integrate",
    "is_stable",
    "ise",
    "itae",
    "kalman_gain",
    "kirkbride_feed_stage",
    "least_squares",
    "linear_feedback",
    "linear_mpc",
    "linearize",
    "liquid_density",
    "liquid_thermal_conductivity",
    "liquid_viscosity",
    "liquid_volumetric_flow",
    "lmtd",
    "lqr",
    "make_stream",
    "mass_flow",
    "meet_spec",
    "minimize",
    "minimum_utilities",
    "mix",
    "molar_enthalpy",
    "molar_entropy",
    "molar_mass",
    "moving_horizon_estimate",
    "nonlinear_feedback",
    "nonlinear_mpc",
    "npv",
    "nrtl_model_for",
    "odeint",
    "odeint_final",
    "optimal_control",
    "optimal_dt_min",
    "optimize_flowsheet",
    "optimize_flowsheet_eo",
    "overshoot",
    "p_only",
    "pfr",
    "pi",
    "pinch_analysis",
    "poles",
    "pressure_factor",
    "pump",
    "purchased_cost",
    "pxy_diagram",
    "quadratic_tracking",
    "reactive_distillation",
    "reactive_flash",
    "relative_volatility",
    "residue_curve",
    "residue_curve_map",
    "rise_time",
    "saft_model_for",
    "saturated_steam_temperature",
    "second_order_step",
    "settling_time",
    "shortcut_column",
    "simulate",
    "simulate_closed_loop",
    "solve_column",
    "solve_design",
    "solve_qp",
    "solve_qp_canonical",
    "splitter",
    "steam_enthalpy",
    "steam_heating",
    "steam_quality_after_letdown",
    "steam_turbine",
    "step_info",
    "stoichiometric_reactor",
    "supertarget",
    "surface_tension",
    "synthesize_network",
    "tear_solve",
    "three_phase_flash",
    "total_annual_cost",
    "total_annual_cost_target",
    "tune_mpc",
    "tune_pid",
    "turbine",
    "txy_diagram",
    "underwood_min_reflux",
    "unifac_model_for",
    "uniquac_model_for",
    "units_target",
    "utility_cost",
    "valve",
    "vapor_density",
    "vapor_molar_volume_ideal",
    "vapor_thermal_conductivity",
    "vapor_viscosity",
    "vapor_volumetric_flow",
    "verify_network",
    "vessel_volume",
    "ziegler_nichols",
]

__version__ = "0.2.0"
