"""Differentiable process-simulation layer for Fugacio (depends on ``fugacio.thermo``).

The layer provides:

* :class:`Stream` -- the differentiable material stream passed between units;
* a stream property bridge (:func:`enthalpy_flow`, :func:`entropy_flow`,
  :func:`molar_enthalpy`, :func:`molar_entropy`, :func:`mass_flow`) that gives any
  stream a two-phase-aware enthalpy/entropy via :mod:`fugacio.thermo`;
* unit operations with rigorous material *and* energy balances
  (:func:`flash_drum`, :func:`heater`, :func:`valve`, :func:`pump`,
  :func:`compressor`, :func:`turbine`, :func:`mix`, :func:`splitter`,
  :func:`component_separator`);
* a thermodynamic-model bridge (:func:`eos_model_for`, :func:`nrtl_model_for`,
  :func:`uniquac_model_for`, :func:`unifac_model_for`) that turns component names
  into a ready EOS or gamma-phi :class:`~fugacio.thermo.EquilibriumModel`;
* non-ideal separation units (:func:`flash_vle`, :func:`decanter`,
  :func:`three_phase_flash`) and binary diagram / azeotrope / residue-curve helpers
  (:func:`pxy_diagram`, :func:`txy_diagram`, :func:`azeotrope_pressure`,
  :func:`azeotrope_temperature`, :func:`residue_curve`, :func:`residue_curve_map`);
* reactor unit operations (:func:`equilibrium_reactor`,
  :func:`stoichiometric_reactor`, :func:`cstr`, :func:`pfr`,
  :func:`batch_reactor`) and reactive separations (:func:`reactive_flash`,
  :func:`reactive_distillation`);
* a differentiable optimization toolkit (:func:`minimize`, :func:`argmin`,
  :func:`least_squares`) that differentiates *through the optimum* by the
  implicit function theorem;
* design specifications and set-point controllers (:func:`meet_spec`,
  :func:`solve_design`, :func:`controller`) that adjust a degree of freedom to
  hit a target, plus end-to-end flowsheet optimization (:func:`optimize_flowsheet`);
* equipment sizing, Turton bare-module costing, utility pricing, and financial
  metrics (:func:`heat_exchanger_area`, :func:`bare_module_cost`,
  :func:`utility_cost`, :func:`total_annual_cost`, :func:`npv`) for money-valued
  design objectives;
* differentiable heat integration / pinch analysis (:func:`pinch_analysis`,
  :func:`composite_curves`, :func:`grand_composite_curve`, :func:`area_target`,
  :func:`optimal_dt_min`, :func:`synthesize_network`) for minimum-utility targets
  and heat-exchanger-network synthesis (see :mod:`fugacio.sim.integration`);
* physical steam/cooling-water utilities on IAPWS-95 steam tables
  (:func:`steam_heating`, :func:`cooling_water`, :func:`steam_turbine`,
  :func:`condensate_flash_fraction`) for utility balances with real latent
  heats, differentiable end to end;
* the original lightweight modified-Raoult helpers (:func:`bubble_pressure`,
  :func:`antoine_psat`).
"""

from fugacio.sim.column import (
    ColumnResult,
    ShortcutResult,
    fenske_min_stages,
    gilliland_stages,
    kirkbride_feed_stage,
    relative_volatility,
    shortcut_column,
    solve_column,
    underwood_min_reflux,
)

# Dynamic simulation & control (time-domain). Imported last; these layers build on
# the steady-state engine above (control depends on the optimizers, the dynamic
# units on the thermodynamic property bridge).
from fugacio.sim.control import (
    PID,
    FOPDTModel,
    PIDState,
    StateSpace,
    StepInfo,
    amigo,
    bode,
    cohen_coon,
    dc_gain,
    first_order_step,
    fit_fopdt,
    fopdt_step,
    frequency_response,
    iae,
    imc_tuning,
    is_stable,
    ise,
    itae,
    linearize,
    overshoot,
    p_only,
    pi,
    poles,
    rise_time,
    second_order_step,
    settling_time,
    step_info,
    ziegler_nichols,
)
from fugacio.sim.design import (
    DesignSpec,
    FlowsheetOptResult,
    SpecResult,
    controller,
    meet_spec,
    optimize_flowsheet,
    solve_design,
)
from fugacio.sim.diagrams import (
    AzeotropeResult,
    PxyDiagram,
    ResidueCurve,
    TxyDiagram,
    azeotrope_pressure,
    azeotrope_temperature,
    pxy_diagram,
    residue_curve,
    residue_curve_map,
    txy_diagram,
)
from fugacio.sim.dynamics import (
    DynamicCSTR,
    DynamicEstimateResult,
    DynamicFlash,
    DynamicFlowsheet,
    DynamicResult,
    DynamicUnit,
    GasReceiver,
    LevelTank,
    MixingTank,
    ODEResult,
    OptimalControlResult,
    ThermalMass,
    estimate_dynamics,
    integrate,
    odeint,
    odeint_final,
    optimal_control,
    simulate,
    tune_pid,
)
from fugacio.sim.economics import (
    CEPCI_DEFAULT,
    CEPCI_REF,
    EquipmentCost,
    Utility,
    annualized_capital,
    bare_module_cost,
    capital_recovery_factor,
    column_diameter,
    column_height,
    cylinder_volume,
    discounted_payback,
    heat_exchanger_area,
    installed_capital,
    lmtd,
    npv,
    pressure_factor,
    purchased_cost,
    total_annual_cost,
    utility_cost,
    vapor_molar_volume_ideal,
    vessel_volume,
)
from fugacio.sim.flowsheet import Flowsheet, tear_solve
from fugacio.sim.integration import (
    CompositeCurves,
    Exchanger,
    GrandComposite,
    HeatCascade,
    HeatExchangerNetwork,
    HeatStream,
    OptimalDtMin,
    PinchResult,
    SuperTargetResult,
    UnitsTarget,
    area_target,
    capital_cost_target,
    composite_curves,
    grand_composite_curve,
    heat_cascade,
    heat_stream,
    make_stream,
    minimum_utilities,
    optimal_dt_min,
    pinch_analysis,
    supertarget,
    synthesize_network,
    total_annual_cost_target,
    units_target,
    verify_network,
)
from fugacio.sim.models import (
    UnifacModel,
    eos_model_for,
    nrtl_model_for,
    unifac_model_for,
    uniquac_model_for,
)
from fugacio.sim.optimize import (
    OptimizeResult,
    argmin,
    least_squares,
    minimize,
)
from fugacio.sim.properties import (
    column_diameter_for,
    enthalpy_flow,
    entropy_flow,
    liquid_density,
    liquid_thermal_conductivity,
    liquid_viscosity,
    liquid_volumetric_flow,
    mass_flow,
    molar_enthalpy,
    molar_entropy,
    molar_mass,
    surface_tension,
    vapor_density,
    vapor_thermal_conductivity,
    vapor_viscosity,
    vapor_volumetric_flow,
)
from fugacio.sim.reactive import (
    ReactiveColumnResult,
    ReactiveFlashResult,
    reactive_distillation,
    reactive_flash,
)
from fugacio.sim.reactors import (
    ReactorResult,
    batch_reactor,
    conversion,
    cstr,
    equilibrium_reactor,
    pfr,
    stoichiometric_reactor,
)
from fugacio.sim.separations import decanter, flash_vle, three_phase_flash
from fugacio.sim.stream import Stream
from fugacio.sim.units import (
    HeaterResult,
    PumpResult,
    WorkResult,
    component_separator,
    compressor,
    flash_drum,
    heater,
    mix,
    pump,
    splitter,
    turbine,
    valve,
)
from fugacio.sim.utilities import (
    STEAM_LEVELS,
    CoolingWaterResult,
    SteamHeatingResult,
    SteamTurbineResult,
    condensate_flash_fraction,
    cooling_water,
    saturated_steam_temperature,
    steam_enthalpy,
    steam_heating,
    steam_quality_after_letdown,
    steam_turbine,
)
from fugacio.sim.vle import antoine_psat, bubble_pressure

__all__ = [
    "CEPCI_DEFAULT",
    "CEPCI_REF",
    "PID",
    "STEAM_LEVELS",
    "AzeotropeResult",
    "ColumnResult",
    "CompositeCurves",
    "CoolingWaterResult",
    "DesignSpec",
    "DynamicCSTR",
    "DynamicEstimateResult",
    "DynamicFlash",
    "DynamicFlowsheet",
    "DynamicResult",
    "DynamicUnit",
    "EquipmentCost",
    "Exchanger",
    "FOPDTModel",
    "Flowsheet",
    "FlowsheetOptResult",
    "GasReceiver",
    "GrandComposite",
    "HeatCascade",
    "HeatExchangerNetwork",
    "HeatStream",
    "HeaterResult",
    "LevelTank",
    "MixingTank",
    "ODEResult",
    "OptimalControlResult",
    "OptimalDtMin",
    "OptimizeResult",
    "PIDState",
    "PinchResult",
    "PumpResult",
    "PxyDiagram",
    "ReactiveColumnResult",
    "ReactiveFlashResult",
    "ReactorResult",
    "ResidueCurve",
    "ShortcutResult",
    "SpecResult",
    "StateSpace",
    "SteamHeatingResult",
    "SteamTurbineResult",
    "StepInfo",
    "Stream",
    "SuperTargetResult",
    "ThermalMass",
    "TxyDiagram",
    "UnifacModel",
    "UnitsTarget",
    "Utility",
    "WorkResult",
    "amigo",
    "annualized_capital",
    "antoine_psat",
    "area_target",
    "argmin",
    "azeotrope_pressure",
    "azeotrope_temperature",
    "bare_module_cost",
    "batch_reactor",
    "bode",
    "bubble_pressure",
    "capital_cost_target",
    "capital_recovery_factor",
    "cohen_coon",
    "column_diameter",
    "column_diameter_for",
    "column_height",
    "component_separator",
    "composite_curves",
    "compressor",
    "condensate_flash_fraction",
    "controller",
    "conversion",
    "cooling_water",
    "cstr",
    "cylinder_volume",
    "dc_gain",
    "decanter",
    "discounted_payback",
    "enthalpy_flow",
    "entropy_flow",
    "eos_model_for",
    "equilibrium_reactor",
    "estimate_dynamics",
    "fenske_min_stages",
    "first_order_step",
    "fit_fopdt",
    "flash_drum",
    "flash_vle",
    "fopdt_step",
    "frequency_response",
    "gilliland_stages",
    "grand_composite_curve",
    "heat_cascade",
    "heat_exchanger_area",
    "heat_stream",
    "heater",
    "iae",
    "imc_tuning",
    "installed_capital",
    "integrate",
    "is_stable",
    "ise",
    "itae",
    "kirkbride_feed_stage",
    "least_squares",
    "linearize",
    "liquid_density",
    "liquid_thermal_conductivity",
    "liquid_viscosity",
    "liquid_volumetric_flow",
    "lmtd",
    "make_stream",
    "mass_flow",
    "meet_spec",
    "minimize",
    "minimum_utilities",
    "mix",
    "molar_enthalpy",
    "molar_entropy",
    "molar_mass",
    "npv",
    "nrtl_model_for",
    "odeint",
    "odeint_final",
    "optimal_control",
    "optimal_dt_min",
    "optimize_flowsheet",
    "overshoot",
    "p_only",
    "pfr",
    "pi",
    "pinch_analysis",
    "poles",
    "pressure_factor",
    "pump",
    "purchased_cost",
    "pxy_diagram",
    "reactive_distillation",
    "reactive_flash",
    "relative_volatility",
    "residue_curve",
    "residue_curve_map",
    "rise_time",
    "saturated_steam_temperature",
    "second_order_step",
    "settling_time",
    "shortcut_column",
    "simulate",
    "solve_column",
    "solve_design",
    "splitter",
    "steam_enthalpy",
    "steam_heating",
    "steam_quality_after_letdown",
    "steam_turbine",
    "step_info",
    "stoichiometric_reactor",
    "supertarget",
    "surface_tension",
    "synthesize_network",
    "tear_solve",
    "three_phase_flash",
    "total_annual_cost",
    "total_annual_cost_target",
    "tune_pid",
    "turbine",
    "txy_diagram",
    "underwood_min_reflux",
    "unifac_model_for",
    "uniquac_model_for",
    "units_target",
    "utility_cost",
    "valve",
    "vapor_density",
    "vapor_molar_volume_ideal",
    "vapor_thermal_conductivity",
    "vapor_viscosity",
    "vapor_volumetric_flow",
    "verify_network",
    "vessel_volume",
    "ziegler_nichols",
]

__version__ = "0.0.1"
