"""Generate ``_formation_data.py``: ideal-gas Gibbs energies of formation.

This is a *one-shot authoring tool*, not part of the package. The curated
database (:mod:`fugacio.thermo.components`) carries an ideal-gas enthalpy of
formation ``hform_ig`` for every component but a Gibbs energy of formation
``gform_ig`` for only the textbook subset. Reaction thermochemistry needs both,
so this script backfills the rest from the open ``thermo`` dataset.

For each component still missing ``gform_ig`` we read the *formation entropy*
``Sf`` (``thermo``'s ``Sfgm``) and combine it with the database's *own*
enthalpy so the pair stays internally consistent::

    gform_ig = hform_ig(database) - T_REF * Sf

That way ``(hform_ig - gform_ig) / T_REF`` reproduces the species formation
entropy exactly, which is what :func:`fugacio.thermo.reactions.delta_s_rxn`
relies on. Elements (He, Ne, ...) come back as ``0`` as they should.

Run with ``uv run --group oracles python scripts/gen_formation.py`` (needs the
optional ``thermo`` package); the emitted values are plain reference data baked
into the source tree and the dependency is not needed at runtime.
"""

from __future__ import annotations

from thermo.chemical import Chemical

from fugacio.thermo.components import DATABASE
from fugacio.thermo.constants import T_REF

OUT = "packages/fugacio-thermo/src/fugacio/thermo/_formation_data.py"

HEADER = '''"""Ideal-gas Gibbs energies of formation (J/mol at 298.15 K).

Auto-generated by ``scripts/gen_formation.py`` from the open ``thermo`` dataset;
do not edit by hand. These backfill ``gform_ig`` for the components whose curated
record in :mod:`fugacio.thermo.components` carries only an enthalpy of formation,
so that reaction thermochemistry (:mod:`fugacio.thermo.reactions`) is available
for them. Each value is derived as ``hform_ig - T_REF * Sf`` from the database's
own enthalpy and the reference formation entropy, keeping the enthalpy/Gibbs pair
self-consistent. The textbook subset that already defines ``gform_ig`` inline is
intentionally absent here.
"""

from __future__ import annotations

#: Component name -> ideal-gas Gibbs energy of formation (J/mol at 298.15 K).
GFORM_IG: dict[str, float] = {
'''


def main() -> None:
    rows: dict[str, float] = {}
    skipped: list[str] = []
    for name, comp in sorted(DATABASE.items()):
        if comp.gform_ig is not None or comp.hform_ig is None:
            continue
        try:
            chem = Chemical(comp.cas or name)
            sf = chem.Sfgm
        except Exception as exc:
            skipped.append(f"{name}: {exc!r}")
            continue
        if sf is None:
            skipped.append(f"{name}: no Sfgm")
            continue
        rows[name] = round(comp.hform_ig - T_REF * float(sf), 1)

    lines = [HEADER]
    for name in sorted(rows):
        lines.append(f"    {name!r}: {rows[name]},\n")
    lines.append("}\n")
    with open(OUT, "w") as fh:
        fh.write("".join(lines))

    print(f"wrote {len(rows)} gform_ig values to {OUT}")
    if skipped:
        print(f"skipped {len(skipped)}:")
        for s in skipped:
            print(" ", s)


if __name__ == "__main__":
    main()
