"""Generate curated cubic-EOS binary interaction parameters (PR ``kij``).

A one-shot authoring tool (not part of the package), companion to
``scripts/gen_parameters.py``. It pulls the Peng-Robinson binary interaction
coefficients ``k_ij`` from the open ChemSep database
(``thermo.interaction_parameters``) for every resolvable pair in the Fugacio
component database, and writes them to ``_eos_params.py``.

These ``k_ij`` correct the EOS van der Waals one-fluid mixing rule for real
mixtures; pairs without a curated value default to zero (ideal mixing). Run with
``uv run --group oracles python scripts/gen_eos_params.py`` (requires the optional
``thermo`` package).
"""

from __future__ import annotations

from thermo import interaction_parameters as ipm

IPDB = ipm.IPDB
EOS_PARAMS_PY = "packages/fugacio-thermo/src/fugacio/thermo/_eos_params.py"


def build() -> None:
    import fugacio.thermo.components as comp

    db = comp.DATABASE
    named = sorted(n for n in db if db[n].cas)

    kij: dict[tuple[str, str], float] = {}
    for i in range(len(named)):
        for j in range(i + 1, len(named)):
            a, b = named[i], named[j]
            cas_pair = [db[a].cas, db[b].cas]
            if IPDB.has_ip_specific("ChemSep PR", cas_pair, "kij"):
                matrix = IPDB.get_ip_asymmetric_matrix("ChemSep PR", cas_pair, "kij")
                value = float(matrix[0][1])
                if value != 0.0:
                    kij[(a, b)] = round(value, 6)

    _write(kij)
    print(f"EOS params: {len(kij)} nonzero PR kij pairs.")


def _write(kij: dict[tuple[str, str], float]) -> None:
    lines = [f"({a!r}, {b!r}): {v}," for (a, b), v in sorted(kij.items())]
    body = "\n".join("    " + line for line in lines)
    src = f'''"""Curated cubic-EOS binary interaction parameters (generated).

Generated by ``scripts/gen_eos_params.py``. The Peng-Robinson binary interaction
coefficients ``k_ij`` are from the open ChemSep database, keyed by name pairs
sorted alphabetically. They enter the van der Waals one-fluid mixing rule as
``a_ij = (1 - k_ij) sqrt(a_i a_j)``; pairs absent here default to ``k_ij = 0``.
Do not edit by hand -- regenerate instead.
"""

from __future__ import annotations

# (name_i, name_j) sorted -> k_ij for Peng-Robinson (symmetric).
PR_KIJ: dict[tuple[str, str], float] = {{
{body}
}}
'''
    with open(EOS_PARAMS_PY, "w") as f:
        f.write(src)


if __name__ == "__main__":
    build()
