"""Differentiable thermodynamics and physical-property engine for Fugacio.

Everything here is written against `jax.numpy`, so gradients flow cleanly
through the rest of the Fugacio stack (``fugacio.sim``, ``fugacio.copilot``).

The public surface is grouped as:

* **data**: `Component`, the curated `DATABASE`, helpers, and a
  NIST ThermoML archive reader (`read_thermoml`, `load_sample`);
* **ideal gas**: `cp_ig`, `enthalpy_ig`, `entropy_ig`;
* **equations of state**: `PR`, `SRK`, `RK`, `VDW`
  plus fugacity-coefficient and volume routines;
* **activity models**: Margules, van Laar, Wilson, NRTL, UNIQUAC, and
  regular-solution / Flory-Huggins, both as functions and as differentiable
  `ActivityModel` objects;
* **group contribution**: `unifac_activity`, `joback_estimate`;
* **reference state**: `liquid_reference_fugacity`,
  `poynting_factor`, `henry_constant`;
* **reference fluids**: `fugacio.thermo.helmholtz`, multiparameter
  Helmholtz EOS of the REFPROP/CoolProp class (IAPWS-95 water/steam,
  Span-Wagner CO2, ...) with differentiable saturation lines, steam-table
  state functions (`state_tp`, `state_ph`, ...), and the IAPWS
  transport formulations for water;
* **property correlations**: DIPPR-form kernels and corresponding-states
  estimators for enthalpy of vaporization and liquid heat capacity
  (`heat_of_vaporization`, `liquid_heat_capacity`), liquid/vapour
  volumetric properties (`liquid_density`, `mixture_liquid_volume`,
  Peneloux translation), and transport properties
  (`gas_viscosities`, `liquid_thermal_conductivities`,
  `surface_tensions`, `gas_diffusivity`, ...), pure and mixture;
* **phase equilibrium**: equation-of-state (`flash_pt`,
  `bubble_pressure_eos`, ...) *and* gamma-phi (`flash_pt_gamma`,
  `bubble_pressure_gamma`, ...) routes, plus liquid-liquid
  (`flash_lle`) and vapour-liquid-liquid (`flash_vlle`,
  `heterogeneous_azeotrope`) equilibria and tangent-plane stability;
* **models**: the unified `EOSModel` / `GammaPhiModel` interface;
* **regression**: differentiable parameter estimation
  (`levenberg_marquardt`, `fit_nrtl_binary`, ...),
  UNIFAC-to-binary prediction (`predict_nrtl_from_unifac`), and the
  ThermoML batch driver / parameter bank (`fit_vle_dataset`,
  `ParameterBank`);
* **reactions**: stoichiometry and standard-state thermochemistry
  (`Reaction`, `reaction_properties`, `equilibrium_constant`),
  chemical-reaction equilibrium
  (`fugacio.thermo.reaction_equilibrium.equilibrium`), and differentiable
  rate laws (`PowerLaw`, `MassActionReversible`, `LHHW`);
* **validation**: consistency laws and finite-difference gradient checks, plus
  `fugacio.thermo.oracles`, optional differential tests against the
  ``thermo`` / ``chemicals`` / Clapeyron.jl (activity) and Cantera (reaction)
  reference libraries.
"""

from fugacio.thermo.activity import (
    NRTL,
    UNIQUAC,
    ActivityModel,
    FloryHuggins,
    Hildebrand,
    Margules,
    RegularSolution,
    VanLaar,
    Wilson,
    excess_gibbs,
    flory_huggins_gamma,
    flory_huggins_ln_gamma,
    gamma,
    hildebrand_ln_gamma,
    margules,
    margules_excess_gibbs,
    margules_gamma,
    margules_ln_gamma,
    nrtl,
    nrtl_from_energies,
    nrtl_gamma,
    nrtl_ln_gamma,
    nrtl_tau,
    regular_solution_gamma,
    regular_solution_ln_gamma,
    uniquac,
    uniquac_from_energies,
    uniquac_gamma,
    uniquac_ln_gamma,
    uniquac_tau,
    van_laar,
    van_laar_gamma,
    van_laar_ln_gamma,
    volume_fractions,
    wilson_gamma,
    wilson_lambda,
    wilson_ln_gamma,
)
from fugacio.thermo.components import (
    DATABASE,
    AntoineCoeffs,
    Component,
    CpIdeal,
    component_arrays,
    get,
    names,
)
from fugacio.thermo.constants import P_REF, T_REF, R
from fugacio.thermo.correlations import (
    dippr100,
    dippr101,
    dippr102,
    dippr105,
    dippr106,
    heat_of_vaporization,
    liquid_heat_capacity,
    mulero_cachadina,
    pitzer_hvap,
    rowlinson_bondi_cp,
    watson_hvap,
)
from fugacio.thermo.data import (
    has_nrtl,
    has_uniquac,
    kij_from_database,
    nrtl_from_database,
    nrtl_params,
    pr_kij,
    uniquac_from_database,
    uniquac_params,
    uniquac_rq,
)
from fugacio.thermo.departure import (
    ResidualProperties,
    residual_cp,
    residual_enthalpy,
    residual_entropy,
    residual_gibbs,
    residual_properties,
)
from fugacio.thermo.energy import (
    EnergyFlashResult,
    flash_ph,
    flash_ps,
    mixture_enthalpy,
    mixture_entropy,
)
from fugacio.thermo.eos import (
    PR,
    RK,
    SRK,
    VDW,
    CubicEOS,
    compressibility,
    ln_phi_mixture,
    ln_phi_pure,
    molar_volume,
    pressure,
)
from fugacio.thermo.equilibrium import (
    FlashResult,
    StabilityResult,
    bubble_pressure_eos,
    dew_pressure_eos,
    flash_pt,
    psat_eos,
    rachford_rice,
    stability_analysis,
    wilson_k,
)
from fugacio.thermo.gammaphi import (
    bubble_pressure_gamma,
    bubble_temperature_gamma,
    dew_pressure_gamma,
    dew_temperature_gamma,
    flash_pt_gamma,
    gamma_phi_k_values,
)
from fugacio.thermo.groupcontrib import (
    joback_estimate,
    modified_unifac_activity,
    unifac_activity,
)
from fugacio.thermo.helmholtz import (
    FluidState,
    HelmholtzFluid,
    SaturationState,
    has_reference_fluid,
    reference_fluid,
    reference_fluid_names,
    saturation_state,
    state_ph,
    state_pq,
    state_ps,
    state_tp,
    state_tq,
    water_thermal_conductivity,
    water_viscosity,
)
from fugacio.thermo.helmholtz import (
    surface_tension as reference_surface_tension,
)
from fugacio.thermo.ideal import (
    cp_ig,
    enthalpy_ig,
    enthalpy_ig_mixture,
    entropy_ig,
    entropy_ig_mixture,
    gibbs_ig,
    gibbs_ig_mixture,
    ideal_gas_coeffs,
)
from fugacio.thermo.kinetics import (
    LHHW,
    Arrhenius,
    MassActionReversible,
    PowerLaw,
    arrhenius,
    arrhenius_ref,
)
from fugacio.thermo.lle import (
    LLEResult,
    binary_binodal,
    binodal_curve,
    flash_lle,
    tie_line,
)
from fugacio.thermo.parameter_bank import (
    FittedBinary,
    ParameterBank,
    fit_bundled_samples,
    fit_vle_dataset,
)
from fugacio.thermo.phase import (
    EOSModel,
    EquilibriumModel,
    GammaPhiModel,
    eos_model,
    gamma_phi_model,
)
from fugacio.thermo.properties import (
    molar_cp,
    molar_enthalpy,
    molar_entropy,
    molar_gibbs,
    speed_of_sound_ideal,
    stable_phase,
)
from fugacio.thermo.reactions import (
    Reaction,
    ReactionProperties,
    delta_g_rxn,
    delta_h_rxn,
    delta_s_rxn,
    equilibrium_constant,
    equilibrium_constant_of,
    parse_reaction,
    reaction_arrays,
    reaction_properties,
    stoichiometry,
)
from fugacio.thermo.reference import (
    antoine_psat,
    henry_constant,
    liquid_reference_fugacity,
    poynting_factor,
    pure_liquid_volumes,
    saturation_fugacity_coefficient,
    saturation_pressures,
)
from fugacio.thermo.regression import (
    activity_residuals,
    bubble_pressure_residuals,
    fit_nrtl_binary,
    fit_uniquac_binary,
    gradient_descent,
    levenberg_marquardt,
    lle_residuals,
    predict_nrtl_from_unifac,
    predict_uniquac_from_unifac,
    unifac_ln_gamma_grid,
)
from fugacio.thermo.stability import (
    TangentPlaneResult,
    liquid_stability,
    stability_analysis_general,
    tangent_plane_distance,
)
from fugacio.thermo.thermoml import (
    Column,
    Compound,
    Dataset,
    ThermoMLData,
    list_samples,
    load_sample,
    read_thermoml,
    sample_path,
)
from fugacio.thermo.transport import (
    brock_bird_surface_tension,
    chung_thermal_conductivity_gas,
    chung_viscosity_gas,
    diffusion_volume,
    dippr9h_mixture,
    fuller_diffusivity,
    gas_diffusivity,
    gas_mixture_thermal_conductivity,
    gas_mixture_viscosity,
    gas_thermal_conductivities,
    gas_viscosities,
    grunberg_nissan_viscosity,
    letsou_stiel_viscosity,
    liquid_diffusivity,
    liquid_mixture_thermal_conductivity,
    liquid_mixture_viscosity,
    liquid_thermal_conductivities,
    liquid_viscosities,
    mixture_surface_tension,
    sato_riedel_thermal_conductivity,
    surface_tensions,
    wassiljewa_mixture,
    wilke_chang_diffusivity,
    wilke_mixture_viscosity,
    winterfeld_scriven_davis,
)
from fugacio.thermo.vlle import (
    HeterogeneousAzeotrope,
    VLLEResult,
    flash_vlle,
    heterogeneous_azeotrope,
)
from fugacio.thermo.volumetric import (
    costald_mixture_volume,
    costald_volume,
    liquid_density,
    liquid_molar_volumes,
    mixture_liquid_volume,
    peneloux_shift,
    rackett_volume,
    translated_liquid_volume_for,
    translated_molar_volume,
    tyn_calus_vb,
    vapor_density,
    zra_estimate,
)

__all__ = [
    "DATABASE",
    "LHHW",
    "NRTL",
    "PR",
    "P_REF",
    "RK",
    "SRK",
    "T_REF",
    "UNIQUAC",
    "VDW",
    "ActivityModel",
    "AntoineCoeffs",
    "Arrhenius",
    "Column",
    "Component",
    "Compound",
    "CpIdeal",
    "CubicEOS",
    "Dataset",
    "EOSModel",
    "EnergyFlashResult",
    "EquilibriumModel",
    "FittedBinary",
    "FlashResult",
    "FloryHuggins",
    "FluidState",
    "GammaPhiModel",
    "HelmholtzFluid",
    "HeterogeneousAzeotrope",
    "Hildebrand",
    "LLEResult",
    "Margules",
    "MassActionReversible",
    "ParameterBank",
    "PowerLaw",
    "R",
    "Reaction",
    "ReactionProperties",
    "RegularSolution",
    "ResidualProperties",
    "SaturationState",
    "StabilityResult",
    "TangentPlaneResult",
    "ThermoMLData",
    "VLLEResult",
    "VanLaar",
    "Wilson",
    "activity_residuals",
    "antoine_psat",
    "arrhenius",
    "arrhenius_ref",
    "binary_binodal",
    "binodal_curve",
    "brock_bird_surface_tension",
    "bubble_pressure_eos",
    "bubble_pressure_gamma",
    "bubble_pressure_residuals",
    "bubble_temperature_gamma",
    "chung_thermal_conductivity_gas",
    "chung_viscosity_gas",
    "component_arrays",
    "compressibility",
    "costald_mixture_volume",
    "costald_volume",
    "cp_ig",
    "delta_g_rxn",
    "delta_h_rxn",
    "delta_s_rxn",
    "dew_pressure_eos",
    "dew_pressure_gamma",
    "dew_temperature_gamma",
    "diffusion_volume",
    "dippr9h_mixture",
    "dippr100",
    "dippr101",
    "dippr102",
    "dippr105",
    "dippr106",
    "enthalpy_ig",
    "enthalpy_ig_mixture",
    "entropy_ig",
    "entropy_ig_mixture",
    "eos_model",
    "equilibrium_constant",
    "equilibrium_constant_of",
    "excess_gibbs",
    "fit_bundled_samples",
    "fit_nrtl_binary",
    "fit_uniquac_binary",
    "fit_vle_dataset",
    "flash_lle",
    "flash_ph",
    "flash_ps",
    "flash_pt",
    "flash_pt_gamma",
    "flash_vlle",
    "flory_huggins_gamma",
    "flory_huggins_ln_gamma",
    "fuller_diffusivity",
    "gamma",
    "gamma_phi_k_values",
    "gamma_phi_model",
    "gas_diffusivity",
    "gas_mixture_thermal_conductivity",
    "gas_mixture_viscosity",
    "gas_thermal_conductivities",
    "gas_viscosities",
    "get",
    "gibbs_ig",
    "gibbs_ig_mixture",
    "gradient_descent",
    "grunberg_nissan_viscosity",
    "has_nrtl",
    "has_reference_fluid",
    "has_uniquac",
    "heat_of_vaporization",
    "henry_constant",
    "heterogeneous_azeotrope",
    "hildebrand_ln_gamma",
    "ideal_gas_coeffs",
    "joback_estimate",
    "kij_from_database",
    "letsou_stiel_viscosity",
    "levenberg_marquardt",
    "liquid_density",
    "liquid_diffusivity",
    "liquid_heat_capacity",
    "liquid_mixture_thermal_conductivity",
    "liquid_mixture_viscosity",
    "liquid_molar_volumes",
    "liquid_reference_fugacity",
    "liquid_stability",
    "liquid_thermal_conductivities",
    "liquid_viscosities",
    "list_samples",
    "lle_residuals",
    "ln_phi_mixture",
    "ln_phi_pure",
    "load_sample",
    "margules",
    "margules_excess_gibbs",
    "margules_gamma",
    "margules_ln_gamma",
    "mixture_enthalpy",
    "mixture_entropy",
    "mixture_liquid_volume",
    "mixture_surface_tension",
    "modified_unifac_activity",
    "molar_cp",
    "molar_enthalpy",
    "molar_entropy",
    "molar_gibbs",
    "molar_volume",
    "mulero_cachadina",
    "names",
    "nrtl",
    "nrtl_from_database",
    "nrtl_from_energies",
    "nrtl_gamma",
    "nrtl_ln_gamma",
    "nrtl_params",
    "nrtl_tau",
    "parse_reaction",
    "peneloux_shift",
    "pitzer_hvap",
    "poynting_factor",
    "pr_kij",
    "predict_nrtl_from_unifac",
    "predict_uniquac_from_unifac",
    "pressure",
    "psat_eos",
    "pure_liquid_volumes",
    "rachford_rice",
    "rackett_volume",
    "reaction_arrays",
    "reaction_properties",
    "read_thermoml",
    "reference_fluid",
    "reference_fluid_names",
    "reference_surface_tension",
    "regular_solution_gamma",
    "regular_solution_ln_gamma",
    "residual_cp",
    "residual_enthalpy",
    "residual_entropy",
    "residual_gibbs",
    "residual_properties",
    "rowlinson_bondi_cp",
    "sample_path",
    "sato_riedel_thermal_conductivity",
    "saturation_fugacity_coefficient",
    "saturation_pressures",
    "saturation_state",
    "speed_of_sound_ideal",
    "stability_analysis",
    "stability_analysis_general",
    "stable_phase",
    "state_ph",
    "state_pq",
    "state_ps",
    "state_tp",
    "state_tq",
    "stoichiometry",
    "surface_tensions",
    "tangent_plane_distance",
    "tie_line",
    "translated_liquid_volume_for",
    "translated_molar_volume",
    "tyn_calus_vb",
    "unifac_activity",
    "unifac_ln_gamma_grid",
    "uniquac",
    "uniquac_from_database",
    "uniquac_from_energies",
    "uniquac_gamma",
    "uniquac_ln_gamma",
    "uniquac_params",
    "uniquac_rq",
    "uniquac_tau",
    "van_laar",
    "van_laar_gamma",
    "van_laar_ln_gamma",
    "vapor_density",
    "volume_fractions",
    "wassiljewa_mixture",
    "water_thermal_conductivity",
    "water_viscosity",
    "watson_hvap",
    "wilke_chang_diffusivity",
    "wilke_mixture_viscosity",
    "wilson_gamma",
    "wilson_k",
    "wilson_lambda",
    "wilson_ln_gamma",
    "winterfeld_scriven_davis",
    "zra_estimate",
]

__version__ = "0.0.1"
