"""Differentiable thermodynamics and physical-property engine for Fugacio.

Everything here is written against :mod:`jax.numpy`, so gradients flow cleanly
through the rest of the Fugacio stack (``fugacio.sim``, ``fugacio.copilot``).

The public surface is grouped as:

* **data** -- :class:`Component`, the curated :data:`DATABASE`, helpers, and a
  NIST ThermoML archive reader (:func:`read_thermoml`, :func:`load_sample`);
* **ideal gas** -- :func:`cp_ig`, :func:`enthalpy_ig`, :func:`entropy_ig`;
* **equations of state** -- :data:`PR`, :data:`SRK`, :data:`RK`, :data:`VDW`
  plus fugacity-coefficient and volume routines;
* **activity models** -- Margules, van Laar, Wilson, NRTL, UNIQUAC, and
  regular-solution / Flory-Huggins, both as functions and as differentiable
  :class:`~fugacio.thermo.activity.models.ActivityModel` objects;
* **group contribution** -- :func:`unifac_activity`, :func:`joback_estimate`;
* **reference state** -- :func:`liquid_reference_fugacity`,
  :func:`poynting_factor`, :func:`henry_constant`;
* **phase equilibrium** -- equation-of-state (:func:`flash_pt`,
  :func:`bubble_pressure_eos`, ...) *and* gamma-phi (:func:`flash_pt_gamma`,
  :func:`bubble_pressure_gamma`, ...) routes, plus liquid-liquid
  (:func:`flash_lle`) and vapour-liquid-liquid (:func:`flash_vlle`,
  :func:`heterogeneous_azeotrope`) equilibria and tangent-plane stability;
* **models** -- the unified :class:`EOSModel` / :class:`GammaPhiModel` interface;
* **regression** -- differentiable parameter estimation
  (:func:`levenberg_marquardt`, :func:`fit_nrtl_binary`, ...) and
  UNIFAC-to-binary prediction (:func:`predict_nrtl_from_unifac`);
* **reactions** -- stoichiometry and standard-state thermochemistry
  (:class:`Reaction`, :func:`reaction_properties`, :func:`equilibrium_constant`),
  chemical-reaction equilibrium
  (:func:`fugacio.thermo.reaction_equilibrium.equilibrium`), and differentiable
  rate laws (:class:`PowerLaw`, :class:`MassActionReversible`, :class:`LHHW`);
* **validation** -- consistency laws and finite-difference gradient checks, plus
  :mod:`fugacio.thermo.oracles`, optional differential tests against the
  ``thermo`` / ``chemicals`` / Clapeyron.jl (activity) and Cantera (reaction)
  reference libraries.
"""

from fugacio.thermo.activity import (
    NRTL,
    UNIQUAC,
    ActivityModel,
    FloryHuggins,
    Hildebrand,
    Margules,
    RegularSolution,
    VanLaar,
    Wilson,
    excess_gibbs,
    flory_huggins_gamma,
    flory_huggins_ln_gamma,
    gamma,
    hildebrand_ln_gamma,
    margules,
    margules_excess_gibbs,
    margules_gamma,
    margules_ln_gamma,
    nrtl,
    nrtl_from_energies,
    nrtl_gamma,
    nrtl_ln_gamma,
    nrtl_tau,
    regular_solution_gamma,
    regular_solution_ln_gamma,
    uniquac,
    uniquac_from_energies,
    uniquac_gamma,
    uniquac_ln_gamma,
    uniquac_tau,
    van_laar,
    van_laar_gamma,
    van_laar_ln_gamma,
    volume_fractions,
    wilson_gamma,
    wilson_lambda,
    wilson_ln_gamma,
)
from fugacio.thermo.components import (
    DATABASE,
    AntoineCoeffs,
    Component,
    CpIdeal,
    component_arrays,
    get,
    names,
)
from fugacio.thermo.constants import P_REF, T_REF, R
from fugacio.thermo.data import (
    has_nrtl,
    has_uniquac,
    kij_from_database,
    nrtl_from_database,
    nrtl_params,
    pr_kij,
    uniquac_from_database,
    uniquac_params,
    uniquac_rq,
)
from fugacio.thermo.departure import (
    ResidualProperties,
    residual_cp,
    residual_enthalpy,
    residual_entropy,
    residual_gibbs,
    residual_properties,
)
from fugacio.thermo.energy import (
    EnergyFlashResult,
    flash_ph,
    flash_ps,
    mixture_enthalpy,
    mixture_entropy,
)
from fugacio.thermo.eos import (
    PR,
    RK,
    SRK,
    VDW,
    CubicEOS,
    compressibility,
    ln_phi_mixture,
    ln_phi_pure,
    molar_volume,
    pressure,
)
from fugacio.thermo.equilibrium import (
    FlashResult,
    StabilityResult,
    bubble_pressure_eos,
    dew_pressure_eos,
    flash_pt,
    psat_eos,
    rachford_rice,
    stability_analysis,
    wilson_k,
)
from fugacio.thermo.gammaphi import (
    bubble_pressure_gamma,
    bubble_temperature_gamma,
    dew_pressure_gamma,
    dew_temperature_gamma,
    flash_pt_gamma,
    gamma_phi_k_values,
)
from fugacio.thermo.groupcontrib import (
    joback_estimate,
    modified_unifac_activity,
    unifac_activity,
)
from fugacio.thermo.ideal import (
    cp_ig,
    enthalpy_ig,
    enthalpy_ig_mixture,
    entropy_ig,
    entropy_ig_mixture,
    gibbs_ig,
    gibbs_ig_mixture,
    ideal_gas_coeffs,
)
from fugacio.thermo.kinetics import (
    LHHW,
    Arrhenius,
    MassActionReversible,
    PowerLaw,
    arrhenius,
    arrhenius_ref,
)
from fugacio.thermo.lle import (
    LLEResult,
    binary_binodal,
    binodal_curve,
    flash_lle,
    tie_line,
)
from fugacio.thermo.phase import (
    EOSModel,
    EquilibriumModel,
    GammaPhiModel,
    eos_model,
    gamma_phi_model,
)
from fugacio.thermo.properties import (
    molar_cp,
    molar_enthalpy,
    molar_entropy,
    molar_gibbs,
    speed_of_sound_ideal,
    stable_phase,
)
from fugacio.thermo.reactions import (
    Reaction,
    ReactionProperties,
    delta_g_rxn,
    delta_h_rxn,
    delta_s_rxn,
    equilibrium_constant,
    equilibrium_constant_of,
    parse_reaction,
    reaction_arrays,
    reaction_properties,
    stoichiometry,
)
from fugacio.thermo.reference import (
    antoine_psat,
    henry_constant,
    liquid_reference_fugacity,
    poynting_factor,
    pure_liquid_volumes,
    saturation_fugacity_coefficient,
    saturation_pressures,
)
from fugacio.thermo.regression import (
    activity_residuals,
    bubble_pressure_residuals,
    fit_nrtl_binary,
    fit_uniquac_binary,
    gradient_descent,
    levenberg_marquardt,
    lle_residuals,
    predict_nrtl_from_unifac,
    predict_uniquac_from_unifac,
    unifac_ln_gamma_grid,
)
from fugacio.thermo.stability import (
    TangentPlaneResult,
    liquid_stability,
    stability_analysis_general,
    tangent_plane_distance,
)
from fugacio.thermo.thermoml import (
    Column,
    Compound,
    Dataset,
    ThermoMLData,
    list_samples,
    load_sample,
    read_thermoml,
    sample_path,
)
from fugacio.thermo.vlle import (
    HeterogeneousAzeotrope,
    VLLEResult,
    flash_vlle,
    heterogeneous_azeotrope,
)

__all__ = [
    "DATABASE",
    "LHHW",
    "NRTL",
    "PR",
    "P_REF",
    "RK",
    "SRK",
    "T_REF",
    "UNIQUAC",
    "VDW",
    "ActivityModel",
    "AntoineCoeffs",
    "Arrhenius",
    "Column",
    "Component",
    "Compound",
    "CpIdeal",
    "CubicEOS",
    "Dataset",
    "EOSModel",
    "EnergyFlashResult",
    "EquilibriumModel",
    "FlashResult",
    "FloryHuggins",
    "GammaPhiModel",
    "HeterogeneousAzeotrope",
    "Hildebrand",
    "LLEResult",
    "Margules",
    "MassActionReversible",
    "PowerLaw",
    "R",
    "Reaction",
    "ReactionProperties",
    "RegularSolution",
    "ResidualProperties",
    "StabilityResult",
    "TangentPlaneResult",
    "ThermoMLData",
    "VLLEResult",
    "VanLaar",
    "Wilson",
    "activity_residuals",
    "antoine_psat",
    "arrhenius",
    "arrhenius_ref",
    "binary_binodal",
    "binodal_curve",
    "bubble_pressure_eos",
    "bubble_pressure_gamma",
    "bubble_pressure_residuals",
    "bubble_temperature_gamma",
    "component_arrays",
    "compressibility",
    "cp_ig",
    "delta_g_rxn",
    "delta_h_rxn",
    "delta_s_rxn",
    "dew_pressure_eos",
    "dew_pressure_gamma",
    "dew_temperature_gamma",
    "enthalpy_ig",
    "enthalpy_ig_mixture",
    "entropy_ig",
    "entropy_ig_mixture",
    "eos_model",
    "equilibrium_constant",
    "equilibrium_constant_of",
    "excess_gibbs",
    "fit_nrtl_binary",
    "fit_uniquac_binary",
    "flash_lle",
    "flash_ph",
    "flash_ps",
    "flash_pt",
    "flash_pt_gamma",
    "flash_vlle",
    "flory_huggins_gamma",
    "flory_huggins_ln_gamma",
    "gamma",
    "gamma_phi_k_values",
    "gamma_phi_model",
    "get",
    "gibbs_ig",
    "gibbs_ig_mixture",
    "gradient_descent",
    "has_nrtl",
    "has_uniquac",
    "henry_constant",
    "heterogeneous_azeotrope",
    "hildebrand_ln_gamma",
    "ideal_gas_coeffs",
    "joback_estimate",
    "kij_from_database",
    "levenberg_marquardt",
    "liquid_reference_fugacity",
    "liquid_stability",
    "list_samples",
    "lle_residuals",
    "ln_phi_mixture",
    "ln_phi_pure",
    "load_sample",
    "margules",
    "margules_excess_gibbs",
    "margules_gamma",
    "margules_ln_gamma",
    "mixture_enthalpy",
    "mixture_entropy",
    "modified_unifac_activity",
    "molar_cp",
    "molar_enthalpy",
    "molar_entropy",
    "molar_gibbs",
    "molar_volume",
    "names",
    "nrtl",
    "nrtl_from_database",
    "nrtl_from_energies",
    "nrtl_gamma",
    "nrtl_ln_gamma",
    "nrtl_params",
    "nrtl_tau",
    "parse_reaction",
    "poynting_factor",
    "pr_kij",
    "predict_nrtl_from_unifac",
    "predict_uniquac_from_unifac",
    "pressure",
    "psat_eos",
    "pure_liquid_volumes",
    "rachford_rice",
    "reaction_arrays",
    "reaction_properties",
    "read_thermoml",
    "regular_solution_gamma",
    "regular_solution_ln_gamma",
    "residual_cp",
    "residual_enthalpy",
    "residual_entropy",
    "residual_gibbs",
    "residual_properties",
    "sample_path",
    "saturation_fugacity_coefficient",
    "saturation_pressures",
    "speed_of_sound_ideal",
    "stability_analysis",
    "stability_analysis_general",
    "stable_phase",
    "stoichiometry",
    "tangent_plane_distance",
    "tie_line",
    "unifac_activity",
    "unifac_ln_gamma_grid",
    "uniquac",
    "uniquac_from_database",
    "uniquac_from_energies",
    "uniquac_gamma",
    "uniquac_ln_gamma",
    "uniquac_params",
    "uniquac_rq",
    "uniquac_tau",
    "van_laar",
    "van_laar_gamma",
    "van_laar_ln_gamma",
    "volume_fractions",
    "wilson_gamma",
    "wilson_k",
    "wilson_lambda",
    "wilson_ln_gamma",
]

__version__ = "0.0.1"
