"""Batch regression of ThermoML datasets into a reusable binary-parameter bank.

This is the bridge between the ThermoML reader (:mod:`fugacio.thermo.thermoml`)
and the differentiable fitters (:mod:`fugacio.thermo.regression`): point it at
parsed documents (or the bundled samples) and it fits a binary activity model to
every isothermal P-x VLE table it can understand, recording the fitted
parameters together with their provenance -- source dataset, temperature range,
point count, and the scaled root-mean-square pressure residual. The collected
:class:`FittedBinary` records form a :class:`ParameterBank` that hands back
ready-to-use :class:`~fugacio.thermo.activity.models.NRTL` models with the
component ordering you ask for.

A bank fitted to the bundled samples ships with the package
(``parameter_bank.json``, regenerated by ``scripts/gen_parameter_bank.py``); load
it with :meth:`ParameterBank.load_bundled`. Components are matched to the
Fugacio database by CAS number, never by name, so document-local naming
quirks ("water (H2O)") cannot mis-assign a dataset.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from importlib.resources import files
from pathlib import Path

import jax.numpy as jnp

from fugacio.thermo.activity.models import NRTL
from fugacio.thermo.components import DATABASE, component_arrays
from fugacio.thermo.regression import fit_nrtl_binary
from fugacio.thermo.thermoml import Dataset, ThermoMLData, list_samples, load_sample

__all__ = [
    "FittedBinary",
    "ParameterBank",
    "fit_bundled_samples",
    "fit_vle_dataset",
]

_BANK_FILENAME = "parameter_bank.json"

_CAS_TO_NAME: dict[str, str] | None = None


def _cas_index() -> dict[str, str]:
    """Map CAS registry number -> database component name (built lazily)."""
    global _CAS_TO_NAME
    if _CAS_TO_NAME is None:
        _CAS_TO_NAME = {c.cas: name for name, c in DATABASE.items() if c.cas is not None}
    return _CAS_TO_NAME


@dataclass(frozen=True)
class FittedBinary:
    """A fitted binary interaction record with its provenance.

    Attributes:
        components: Database names ``(1, 2)`` in the orientation of ``b12``/``b21``.
        model: Activity-model family (currently always ``"nrtl"``).
        alpha: The fixed NRTL non-randomness parameter used in the fit.
        b12, b21: Fitted ``tau = b/T`` interaction coefficients (K).
        t_min, t_max: Temperature range of the underlying data (K).
        n_points: Number of data rows fitted.
        rmse: Root-mean-square residual of ``(P_pred - P_exp) / mean(P_exp)``.
        source: Provenance string (sample name or document citation).
    """

    components: tuple[str, str]
    model: str
    alpha: float
    b12: float
    b21: float
    t_min: float
    t_max: float
    n_points: int
    rmse: float
    source: str

    def nrtl(self) -> NRTL:
        """The fitted model as a ready-to-evaluate two-component NRTL."""
        zeros = jnp.zeros((2, 2))
        return NRTL(
            a=zeros,
            b=jnp.array([[0.0, self.b12], [self.b21, 0.0]]),
            alpha=jnp.array([[0.0, self.alpha], [self.alpha, 0.0]]),
            e=zeros,
        )


def _resolve_names(data: ThermoMLData, dataset: Dataset) -> list[str]:
    """Database component names for a dataset, matched by CAS number."""
    index = _cas_index()
    names: list[str] = []
    for org in dataset.components:
        compound = data.compound(org)
        if compound.cas is None or compound.cas not in index:
            raise KeyError(
                f"compound {compound.name or org!r} (CAS {compound.cas}) is not in the "
                f"Fugacio component database"
            )
        names.append(index[compound.cas])
    return names


def fit_vle_dataset(
    data: ThermoMLData,
    dataset: Dataset,
    *,
    alpha: float = 0.3,
    source: str = "",
    max_iter: int = 80,
) -> FittedBinary:
    """Fit binary NRTL ``b`` parameters to one parsed P-x VLE dataset.

    The dataset must be binary with a temperature column, a composition column
    for its first component, and a pressure column (the layout of every bundled
    VLE sample and of archive isothermal P-x tables).

    Returns:
        The :class:`FittedBinary` record, oriented so component 1 is the
        dataset's first component.

    Raises:
        ValueError: if the dataset is not a binary P-x table.
        KeyError: if a compound cannot be matched to the component database.
    """
    if len(dataset.components) != 2:
        raise ValueError(f"expected a binary dataset, got {len(dataset.components)} components")
    names = _resolve_names(data, dataset)
    t = jnp.array(dataset.temperature())
    x1 = jnp.array(dataset.mole_fraction(dataset.components[0]))
    x = jnp.stack([x1, 1.0 - x1], axis=1)
    p = jnp.array(dataset.pressure())

    arr = component_arrays(names)
    model, cost = fit_nrtl_binary(
        t, x, p, arr["tc"], arr["pc"], arr["omega"], alpha=alpha, max_iter=max_iter
    )
    m = int(x.shape[0])
    return FittedBinary(
        components=(names[0], names[1]),
        model="nrtl",
        alpha=alpha,
        b12=float(model.b[0, 1]),
        b21=float(model.b[1, 0]),
        t_min=float(jnp.min(t)),
        t_max=float(jnp.max(t)),
        n_points=m,
        rmse=math.sqrt(2.0 * float(cost) / m),
        source=source,
    )


def _is_binary_vle(dataset: Dataset) -> bool:
    if len(dataset.components) != 2:
        return False
    has_t = dataset.find_column(kind="eTemperature") is not None
    has_x = (
        dataset.find_column(kind="eComponentComposition", component=dataset.components[0])
        is not None
    )
    has_p = dataset.find_column(kind="ePressure") is not None or any(
        "pressure" in c.quantity.lower() for c in dataset.columns
    )
    return has_t and has_x and has_p


def fit_bundled_samples(
    names: list[str] | None = None, *, alpha: float = 0.3
) -> list[FittedBinary]:
    """Fit every binary P-x VLE dataset among the bundled ThermoML samples.

    Non-VLE samples (pure-component tables, missing columns) are skipped, so the
    driver can be pointed at the whole sample directory. This is the batch
    regression behind the bundled parameter bank.
    """
    fitted: list[FittedBinary] = []
    for name in names if names is not None else list_samples():
        data = load_sample(name)
        for dataset in data.datasets:
            if not _is_binary_vle(dataset):
                continue
            fitted.append(fit_vle_dataset(data, dataset, alpha=alpha, source=name))
    return fitted


class ParameterBank:
    """A lookup table of fitted binary parameters, keyed by component pair.

    Pairs are stored orientation-free: :meth:`get` and :meth:`nrtl` accept the
    components in either order and return parameters oriented as *requested*
    (swapping ``b12``/``b21`` when needed).
    """

    def __init__(self, entries: list[FittedBinary]) -> None:
        self._by_pair: dict[frozenset[str], FittedBinary] = {}
        for entry in entries:
            key = frozenset(entry.components)
            # Last write wins; with the bundled bank each pair appears once.
            self._by_pair[key] = entry

    @property
    def entries(self) -> list[FittedBinary]:
        """All records, sorted by component pair for stable iteration."""
        return [self._by_pair[k] for k in sorted(self._by_pair, key=sorted)]

    def __len__(self) -> int:
        return len(self._by_pair)

    def __contains__(self, pair: tuple[str, str]) -> bool:
        return frozenset(pair) in self._by_pair

    def get(self, component_1: str, component_2: str) -> FittedBinary | None:
        """The record for a pair, reoriented so ``component_1`` is component 1."""
        entry = self._by_pair.get(frozenset((component_1, component_2)))
        if entry is None:
            return None
        if entry.components == (component_1, component_2):
            return entry
        return FittedBinary(
            components=(component_1, component_2),
            model=entry.model,
            alpha=entry.alpha,
            b12=entry.b21,
            b21=entry.b12,
            t_min=entry.t_min,
            t_max=entry.t_max,
            n_points=entry.n_points,
            rmse=entry.rmse,
            source=entry.source,
        )

    def nrtl(self, component_1: str, component_2: str) -> NRTL:
        """A ready NRTL model for the pair, in the requested component order.

        Raises:
            KeyError: if the bank has no record for the pair.
        """
        entry = self.get(component_1, component_2)
        if entry is None:
            raise KeyError(f"no fitted parameters for ({component_1!r}, {component_2!r})")
        return entry.nrtl()

    # --- serialization ---------------------------------------------------------

    def to_json(self) -> str:
        """Serialize the bank (sorted, human-diffable)."""
        payload = {
            "format": "fugacio-parameter-bank",
            "version": 1,
            "entries": [asdict(e) for e in self.entries],
        }
        return json.dumps(payload, indent=2) + "\n"

    @classmethod
    def from_json(cls, text: str) -> ParameterBank:
        """Inverse of :meth:`to_json`."""
        payload = json.loads(text)
        entries = [
            FittedBinary(**{**raw, "components": tuple(raw["components"])})
            for raw in payload["entries"]
        ]
        return cls(entries)

    @classmethod
    def load_bundled(cls) -> ParameterBank:
        """The bank fitted to the bundled ThermoML samples (ships with the package)."""
        path = Path(str(files("fugacio.thermo").joinpath(_BANK_FILENAME)))
        return cls.from_json(path.read_text())
